<%@ Page Title="" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="deleteBooking.aspx.cs" Inherits="customer_deleteBooking" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" Runat="Server">
    <style type="text/css">
    .style1
    {
        width: 100%;
    }
    .style2
    {
            width: 258px;
        }
    .style3
    {
        color: #FFFFFF;
        height: 40px;
    }
    .style4
    {
        width: 258px;
        height: 40px;
    }
    .style5
    {
        height: 40px;
    }
</style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">
    <table class="style1">
    <tr>
        <td class="style4">
        </td>
        <td class="style3">
            <h2>
                DELETE BOOKING</h2>
        </td>
        <td class="style5">
        </td>
    </tr>
    <tr>
        <td class="style2">
            &nbsp;</td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
    </tr>
    <tr>
        <td class="style2">
            &nbsp;</td>
        <td>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                AutoGenerateDeleteButton="True" DataSourceID="SqlDataSource1" 
                style="color: #FFFFFF; font-weight: 700" DataKeyNames="bk_id">
                <Columns>
                    <asp:BoundField DataField="bk_id" HeaderText="Id" InsertVisible="False" 
                        SortExpression="bk_id" />
                    <asp:BoundField DataField="bk_time" HeaderText="Time" 
                        SortExpression="bk_time" />
                    <asp:BoundField DataField="bk_datePlaced" HeaderText="Date_Placed" 
                        SortExpression="bk_datePlaced" />
                    <asp:BoundField DataField="bk_ServiceDate" HeaderText="Service_Date" 
                        SortExpression="bk_ServiceDate" />
                    <asp:BoundField DataField="bk_washType" HeaderText="Wash_Type" 
                        SortExpression="bk_washType" />
                    <asp:BoundField DataField="bk_addOns" HeaderText="Add_Ons" 
                        SortExpression="bk_addOns" />
                    <asp:BoundField DataField="bk_cost" HeaderText="Cost" 
                        SortExpression="bk_cost" />
                    <asp:BoundField DataField="fk_custID" HeaderText="Customer_ID" 
                        SortExpression="fk_custID" />
                </Columns>
            </asp:GridView>
        </td>
        <td>
            &nbsp;</td>
    </tr>
</table>
<asp:SqlDataSource ID="SqlDataSource1" runat="server" 
    ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
    DeleteCommand="DELETE FROM sepvens.tbl_booking
where bk_id=?" 
    ProviderName="<%$ ConnectionStrings:ConnectionString.ProviderName %>" 
    SelectCommand="SELECT sepvens.tbl_booking.* FROM sepvens.tbl_booking">
    <DeleteParameters>
        <asp:ControlParameter ControlID="GridView1" Name="bk_id" 
            PropertyName="SelectedValue" />
    </DeleteParameters>
</asp:SqlDataSource>
</asp:Content>

